# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            bH
tagline:          badHorowitz.
description:      Value divulged makes a better world. 'Posts, musings and tutorials on things that bring an interest. Hyde theme made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://badhorowitz.github.io
baseurl:          

author:
  name:           'badhorowitz'
  url:            youtube.com/channel/UCqk8I0BUEzCqOUE2Npukt_w

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
