# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            bH
tagline:          badHorowitz.
description:      Tutrials and musings. Check out my <a href="https://www.youtube.com/channel/UCqk8I0BUEzCqOUE2Npukt_w">Youtube</a> channel.
url:              https://badhorowitz.github.io
baseurl:          

author:
  name:           'badhorowitz'
  url:            youtube.com/channel/UCqk8I0BUEzCqOUE2Npukt_w

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
